/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5e31ae67-b925-4024-88c1-acf2b9bebcbc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_AH3BN7JSD",
    "aws_user_pools_web_client_id": "527789gp6gqohu8urp3g83ivtk",
    "oauth": {}
};


export default awsmobile;
